project_name: zeus

before:
  hooks:
  - go mod download

builds:
  - main: ./cmd/zeus/
    binary: zeus
    goos: [windows, linux,darwin]
    goarch: [amd64, '386', arm, arm64]
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    env:
    - CGO_ENABLED=0

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{- end }}
      {{- .Arch }}"
    wrap_in_directory: false
    format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: 5amu
    name: zeus